In [ ]:
ssp_dat = np.full((3,yrs.size,),np.nan)
ssp_dat[:,Yind] = pcntle

In [1]:
#SHortcut to adding dimensions
#Modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import netCDF4 as nc
from pandas.plotting import table 
from netCDF4 import Dataset
years = [1,2,3]
samples = [11,22,33,44,55,66,77]

nc_filename = "TT_globalsl.nc"
rootgrp = Dataset(nc_filename, "w", format="NETCDF4")
#Define Dimensions

year_dim = rootgrp.createDimension("years", 3)
samp_dim = rootgrp.createDimension("samples", 7)
loc_dim  = rootgrp.createDimension("locations", 1)
loc_var  = rootgrp.createVariable("locations", "i8", ("locations",))

# Populate dimension variables
year_var = rootgrp.createVariable("years", "i4", ("years",))
samp_var = rootgrp.createVariable("samples", "i8", ("samples",))
# samps = rootgrp.createVariable("sea_level_change", "f4", ("samples", "years", "locations"), zlib=True, least_significant_digit=2)
samps = rootgrp.createVariable("sea_level_change", "f4", ("samples", "years","locations"), zlib=True, least_significant_digit=2)
sampsT = rootgrp.createVariable("sea_level_changeT", "f4", ("years","samples","locations"), zlib=True, least_significant_digit=2)





In [4]:
import numpy as np
np.random.seed(10)

dum = np.random.randint(5, size=(3, 7))
print(dum[:,:])
print('--> \n')

samps[:,:,:] = np.transpose(dum[:,:,np.newaxis],(1,0,2))
# sampsT[:,:,:] = np.transpose(dum[:,:,np.newaxis])
print(samps[:,:,0])
# print('--> \n')
# print(sampsT[:,:,0])

# # print(samps1)
# print(samps.shape)
# print(sampsT.shape)
# # print('-----')
# # # dum22 = dum2[:,:,np.newaxis]
# # # print[dum22]

[[1 4 0 1 3 4 1]
 [0 1 2 0 1 0 2]
 [0 4 3 0 4 3 0]]
--> 

[[1. 0. 0.]
 [4. 1. 4.]
 [0. 2. 3.]
 [1. 0. 0.]
 [3. 1. 4.]
 [4. 0. 3.]
 [1. 2. 0.]]


/home/pk695/000_swre/miniconda/envs/facts37/lib/python3.7/site-packages/ipykernel_launcher.py:10: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  # Remove the CWD from sys.path while we load stuff.


In [112]:
samps[:,0,0]

/home/pk695/000_swre/miniconda/envs/facts37/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


masked_array(data=[1., 1., 1., 2., 0., 4., 4.],
             mask=False,
       fill_value=1e+20,
            dtype=float32)

In [89]:
rootgrp.close()